### ISSUE TITLE
no save button

### ISSUE THREAD

**Issue by g7AzaZLO** [TheBodger/MMM-ModulePosition#1]
After adding the module and launching the mirror, I found that I did not have a save button and a slider to turn on / off the grid, while changing the size and location of the modules itself works. What could be the problem?

The second problem is that after changing the module, all text is aligned to the left, not in the middle.

I also really want you to add the ability to save modified modules without deleting files manually. That is, so that I press the save button and the mirror continues to work with already changed modules

Missing button
![image](https://user-images.githubusercontent.com/59707245/197615639-5a5b4639-b209-4df6-9a65-0c9cc6267e3a.png)

Text is left aligned after changing
![image](https://user-images.githubusercontent.com/59707245/197615868-0d173547-05ef-4453-a166-3e4f190ea98e.png)

**Comment by TheBodger** [comment]
i have tested the latest version on github with edge/chrome browser and Save button and jump to Grid option are OK.

Can you let me know how you are running magic mirror, how you start it, the operating system.

when you copy the CSS data created into the custom CSS, the text will be aligned as defined by the module, so clock will appear in the new position with the text aligned in the centre. here is an example after i moved the clock and  added the css to custom.css
 
![Untitled](https://user-images.githubusercontent.com/41484656/197626492-759e52f5-ab5c-4ff0-b9f0-cdb464c0688d.png)

.clock {
    left: -64.5px;
    top: -538px;
    width: 395px;
    height: 142px;
    position: absolute !important; /*included to overide the transition static positioning that is added inline */
}

**Comment by g7AzaZLO** [comment]
I'm using last version of Ubuntu. I did everything according to the instructions. I run it through the console

**Comment by g7AzaZLO** [comment]
I figured out the problem! It was necessary to register your module to ignore the MMM-Carousel module

![image](https://user-images.githubusercontent.com/59707245/197643116-1ff02384-7c93-47a4-a3c9-5215d46dc9e7.png)

It would be very cool if you could add the ability to automatically write to the css file, or even the module to work without restarting the mirror. As well as the ability to change the position and size through some settings button. It would be amazing

Thank you very much for your work

**Comment by TheBodger** [comment]
Thanks for finding this, I will add to the readme. I will look at the possibility of automating the use of the CSS
