### ISSUE TITLE
Module contents get pushed to the left inside of layout area when area is repositioned up or down.

### ISSUE THREAD

**Issue by mishmanPi** [TheBodger/MMM-ModulePosition#2]
Great module and very convenient for customization of my module positions. Only thing I am stuck on figuring out is how to stop and/or fix a module contents that gets changed from a center alignment within the module layout to a left side alignment in the layout. Some of my modules content I want centered across the full width of the screen but when I reposition the module area up or down it moves all of the module contents to the left side of the module layout area.

**Comment by TheBodger** [comment]
I will have a look and get back to you - if possible could you share the config for the module in question 

thanks

**Comment by mishmanPi** [comment]
Here are two screen captures to further explain what happens:
This is how my modules arrangement first appears:
![2023-08-07-162955_1920x1080_scrot](https://github.com/TheBodger/MMM-ModulePosition/assets/141668421/bbb14224-684b-4738-82ab-5a0b8f0f1744)
You can see here that the stock market module and the two bottom news feeds modules contents move to the left after I reposition those modules:
 ![2023-08-07-163041_1920x1080_scrot](https://github.com/TheBodger/MMM-ModulePosition/assets/141668421/ef3c6a2e-9e6c-4c2e-b6bc-4465c5a651c0)

This is the code at the end of my config file:
			{
			module: "MMM-ModulePosition",
			position: "fullscreen_below",
		},

**Comment by TheBodger** [comment]
Do the modules still appear incorrect when you add the saved CSS to custom css and you remove the positioning module from the config ?

I saw similar behaviour in the positioning module but it was ok when I removed the module and added the saved css

**Comment by mishmanPi** [comment]
I was afraid to apply the custom positioning.
I am relatively new to using a Raspberry Pi and MagicMirror.
If the positioning isn't correct, will it restore to original if I remove the custom css?

**Comment by TheBodger** [comment]
Yes it will

The custom.css file in the CSS folder is usually empty

I would rename it to custom.css.ok  and then copy the saved css from the positioning module folder css and rename it to custom.css

If it doesn’t work as you expect, delete the new custom.css and rename the custom.css.ok to custom.css

All will be back to the way it was

Understand the concern, if you need any help just let me know

thanks

**Comment by mishmanPi** [comment]
I applied the settings to the custom.css and the formatting and positions all appeared as I wanted.
So I guess the only thing is when working on the repositioning it isn't necessarily WSIWG. Thanks for the prompt and helpful responses.

**Comment by TheBodger** [comment]
Thanks - will add these findings to the documentation
