### ISSUE TITLE
how save?

### ISSUE THREAD

**Issue by mirrormonark** [TheBodger/MMM-ModulePosition#3]
hello i'm trying this module, i set the grid and hit the save button after i've made the change but it doesn't work. i don't understand what i'm doing wrong. can i point out a couple of things. 
hardware: 
- raspberry pi4 debian bulleyes 32 bit
software:
magicmirror 2.25 (the last version)
node 20
npm 10.1
currently using mmm-page-indicator and mmm-page-selector

**Comment by TheBodger** [comment]
Hi, thanks for using the MM module. 

After you have saved the changes, have you copied the information from the saved css file into the custom.css file ?  Have a look at the instructions [here](https://github.com/TheBodger/MMM-ModulePosition#saving-and-using-customcss). If you still have questions let me know here. Thanks again
