### ISSUE TITLE
MMM-Carousel not able to move to next page

### ISSUE THREAD

**Issue by piccolo456** [TheBodger/MMM-ModulePosition#4]
I can edit the first page in the carousel but when I click on the right arrow to advance to the next page the click is ignored and MM stay on page 1. 

IS there a special key press to activate the carousel buttons.

**Comment by TheBodger** [comment]
Hi 

can you share your config.js or the just entry for carousel and keybindings. and can you let me know which carousel you are using (there appear to be at least 3 different versions - i want to make sure i look at the same one as you)

thanks

**Comment by piccolo456** [comment]
Thanks for the quick reply. I don't use any key bindings with MMM-Carousel only the onscreen buttons (I think this my be the issue).  I did find a workaround I just reordered my slides in the carousel to have the first slide as the one I want to edit, and so I just change page one. 

Below is a portion of my config.js file. 

`		{
           module: "MMM-Carousel",
           position: "bottom_bar", // Required only for navigation controls
           config: {
             transitionInterval: 0,
             showPageIndicators: true,
             showPageControls: true,
		   ignoreModules: ['MMM-ModulePosition',"clock"],
             mode: "slides",
             slides: {
			 main: [{name:"calendar" ,carouselId: 'small_calendar'} , "MMM-CalendarExt3", "MMM-AccuWeatherForecastDeluxe",{name:"MMM-EasyBack" ,carouselId: 'Page3'}],
               "Slide 2": [
			   "MMM-CalendarExt3Agenda","MMM-Todoist",
			   {name:"MMM-EasyBack" ,carouselId: 'Page2'},{name:"MMM-EasyPix" ,carouselId: 'Page4'},
               ],
               "Slide 3": [ "MMM-AccuWeatherForecastDeluxe",{name:"MMM-EasyBack" ,carouselId: 'Page1'},
				   {name:"calendar" ,carouselId: 'big_calendar'},"MMM-Strava"]
             }
           }
         },
		 
		 {
			module: "MMM-ModulePosition",
			position: "fullscreen_below",
		},`

**Comment by TheBodger** [comment]
Thanks for the info - i can see what you are seeing. without a lot of effort i am not sure i can even work out why the arrows are disabled, let alone work out a fix. So i am glad you found a workaround,

There is another workaround, if you set transitionInterval: 10000, or similar, then the different slides will show automatically. as each slide shows, moduleposition will work with whatever is visible and you can rearrange the layout as normal. It will capture new positions/sizes for  ALL modules across multiple slides in one edit session.

thanks for letting me know and if i can help in any other way let me know.
